# syntax=docker/dockerfile:1.8

# Prepare node
FROM node:24-trixie-slim AS node
# Remove symlinks to yarn v1
# See https://github.com/nodejs/docker-node/blob/main/24/trixie-slim/Dockerfile
RUN rm /usr/local/bin/yarn*

# Prepare a base image for building Ruby and for installing gems which may
# require native extensions
FROM debian:trixie-20260316-slim AS build-deps
SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN apt-get update && \
  apt-get install -y --no-install-recommends \
  build-essential curl ca-certificates \
  pkg-config \
  ;

# Build ruby
FROM build-deps AS ruby
RUN apt-get install -y --no-install-recommends \
  rustc \
  libffi-dev libgmp-dev libjemalloc-dev libssl-dev libyaml-dev zlib1g-dev \
  ;

WORKDIR /root/ruby
RUN curl -L https://cache.ruby-lang.org/pub/ruby/4.0/ruby-4.0.5.tar.gz | \
  tar xz --strip-components=1
RUN ./configure \
  --prefix=/opt/ruby \
  --disable-install-doc \
  --with-jemalloc \
  --enable-yjit \
  && \
  make -j8 && \
  make install

# Build libvips
FROM build-deps AS libvips
RUN apt-get install -y --no-install-recommends \
  meson \
  # libvips components
  libglib2.0-dev \
  libcgif-dev \
  libexif-dev \
  libexpat1-dev \
  libgirepository1.0-dev \
  libheif-dev \
  libhwy-dev \
  libimagequant-dev \
  libjpeg62-turbo-dev \
  liblcms2-dev \
  libspng-dev \
  libtiff-dev \
  libwebp-dev \
  ;

WORKDIR /root/libvips
ARG VIPS_VERSION=8.18.3
RUN curl -L https://github.com/libvips/libvips/releases/download/v${VIPS_VERSION}/vips-${VIPS_VERSION}.tar.xz | \
  tar xJ --strip-components=1
RUN meson setup build \
  --prefix=/opt/libvips \
  --libdir=lib \
  -Ddeprecated=false \
  -Dintrospection=disabled \
  -Dmodules=disabled \
  -Dexamples=false \
  && \
  cd build && \
  meson compile && \
  meson install

# Build ffmpeg
FROM build-deps AS ffmpeg
RUN apt-get install -y --no-install-recommends \
  autoconf automake libtool nasm \
  # ffmpeg components
  zlib1g-dev \
  libdav1d-dev \
  libmp3lame-dev \
  libopus-dev \
  libsnappy-dev \
  libvorbis-dev \
  libvpx-dev \
  libwebp-dev \
  libx264-dev \
  libx265-dev \
  ;

WORKDIR /root/ffmpeg
ARG FFMPEG_VERSION=8.1.2
RUN curl -L https://ffmpeg.org/releases/ffmpeg-${FFMPEG_VERSION}.tar.xz | \
  tar xJ --strip-components=1
RUN ./configure \
  --prefix=/opt/ffmpeg \
  --toolchain=hardened \
  --enable-gpl \
  --enable-version3 \
  --disable-static \
  --enable-shared \
  --disable-debug \
  --disable-ffplay \
  --disable-doc \
  --disable-network \
  --disable-devices \
  --enable-libdav1d \
  --enable-libmp3lame \
  --enable-libopus \
  --enable-libsnappy \
  --enable-libvorbis \
  --enable-libvpx \
  --enable-libwebp \
  --enable-libx264 \
  --enable-libx265 \
  --enable-zlib \
  && \
  make -j8 && \
  make install

# Install runtime dependencies
FROM ruby AS precompile-deps
RUN apt-get update && \
  apt-get install -y --no-install-recommends \
  # Ruby dependencies
  git \
  libicu-dev \
  libidn-dev \
  libpq-dev \
  shared-mime-info \
  # Node dependencies
  python3 \
  # Asset compilation dependencies
  libvips42t64 \
  ;
COPY --link --from=node /usr/local/bin /usr/local/bin
COPY --link --from=node /usr/local/lib /usr/local/lib
ENV PATH="${PATH}:/opt/ruby/bin"

COPY Gemfile* package.json yarn.lock .yarnrc.yml /opt/mastodon/
COPY streaming/package.json /opt/mastodon/streaming/

WORKDIR /opt/mastodon
RUN bundle config set --local deployment 'true' && \
  bundle config set --local without 'development test' && \
  bundle config set --local silence_root_warning true && \
  bundle install -j8
RUN corepack enable && \
  corepack install && \
  yarn workspaces focus --all --production

# Precompile rails assets
FROM precompile-deps AS precompile
COPY . /opt/mastodon/
RUN \
  RAILS_ENV="production" \
  NODE_ENV="production" \
  SECRET_KEY_BASE_DUMMY=1 \
  bundle exec rails assets:precompile

# Build the final image
FROM debian:trixie-slim
ARG UID="991"
ARG GID="991"

RUN groupadd -g "${GID}" mastodon && \
  useradd -l -u "$UID" -g "${GID}" -m -d /opt/mastodon mastodon && \
  ln -s /opt/mastodon /mastodon
RUN apt-get update && \
  apt-get install -y --no-install-recommends \
  ca-certificates \
  tzdata \
  libffi8 libgmp10 libjemalloc2 openssl libyaml-0-2 zlib1g \
  libicu76 \
  libidn12 \
  libpq5 \
  file \
  # Docker dependencies
  procps \
  wget \
  tini \
  # For libvips
  libglib2.0-0t64 \
  libcgif0 \
  libexif12 \
  libexpat1 \
  libheif1 \
  libhwy1t64 \
  libimagequant0 \
  libjpeg62-turbo \
  liblcms2-2 \
  libspng0 \
  libtiff6 \
  libwebp7 \
  libwebpdemux2 \
  libwebpmux3 \
  # For ffmpeg
  libdav1d7 \
  libmp3lame0 \
  libopencore-amrnb0 \
  libopencore-amrwb0 \
  libopus0 \
  libsnappy1v5 \
  libtheora0 \
  libvorbis0a \
  libvorbisenc2 \
  libvorbisfile3 \
  libvpx9 \
  libwebp7 \
  libwebpdemux2 \
  libwebpmux3 \
  libx264-164 \
  libx265-215 \
  ;

COPY --link --from=ruby /opt/ruby /opt/ruby
COPY --link --from=node /usr/local/bin /usr/local/bin
COPY --link --from=node /usr/local/lib /usr/local/lib
COPY --link --from=libvips /opt/libvips/bin /usr/local/bin
COPY --link --from=libvips /opt/libvips/lib /usr/local/lib
COPY --link --from=ffmpeg /opt/ffmpeg/bin /usr/local/bin
COPY --link --from=ffmpeg /opt/ffmpeg/lib /usr/local/lib
RUN ldconfig && \
  ldd /usr/local/bin/vips && \
  vips -v && \
  ldd /usr/local/bin/ffmpeg && \
  ffmpeg -version

COPY --chown=mastodon:mastodon . /opt/mastodon
COPY --chown=mastodon:mastodon --from=precompile /opt/mastodon /opt/mastodon

WORKDIR /opt/mastodon
RUN corepack enable && \
  corepack install

# Set the run user
USER mastodon
ENV PATH="${PATH}:/opt/ruby/bin:/opt/mastodon/bin" \
  RUBY_YJIT_ENABLE="1" \
  RAILS_ENV="production" \
  NODE_ENV="production" \
  RAILS_SERVE_STATIC_FILES="true" \
  MASTODON_SIDEKIQ_READY_FILENAME="sidekiq_process_has_started_and_will_begin_processing_jobs" \
  MASTODON_VERSION_PRERELEASE="" \
  MASTODON_VERSION_METADATA="nnn" \
  GITHUB_REPOSITORY="rhenium/mastodon" \
  SOURCE_TAG="nnn"

# Precompile bootsnap code for faster Rails startup
RUN bundle exec bootsnap precompile --gemfile app/ lib/

# Set the work dir and the container entry point
ENTRYPOINT ["/usr/bin/tini", "--"]
EXPOSE 3000 4000
